module.exports = [
  'N/A',
  'Accounting',
  'Advertising',
  'Brand Marketing',
  'Brand Strategy',
  'Business Development',
  'Communications',
  'Consulting',
  'Corporate Strategy',
  'Corporate Banking',
  'Corporate Law',
  'Data Analysis',
  'Digital Marketing',
  'Environmental Consulting',
  'Finance',
  'Financial Services',
  'Financial Technology',
  'Healthtech Consulting',
  'Healthcare Management',
  'Human Resources Consulting',
  'Investment Banking',
  'Law',
  'Management Consulting',
  'Marketing',
  'Product Design',
  'Product Management',
  'Project Management',
  'Public Relations',
  'Social Impact Consulting',
  'Software Development',
  'Software Engineering',
  'Strategy Consulting',
  'Tax M&A',
  'Technology Consulting',
  'UX Design',
  'Wholesale Credit'
];
