module.exports = [
  { label: 'N/A', value: '' },
  { label: 'Accounting', value: 'accounting' },
  { label: 'Advertising', value: 'advertising' },
  { label: 'Brand Marketing', value: 'b-marketing' },
  { label: 'Brand Strategy', value: 'b-strategy' },
  { label: 'Business Development', value: 'biz-development' },
  { label: 'Communications', value: 'communications' },
  { label: 'Consulting', value: 'consulting' },
  { label: 'Corporate Strategy', value: 'c-strategy' },
  { label: 'Corporate Banking', value: 'c-banking' },
  { label: 'Corporate Law', value: 'c-law' },
  { label: 'Data Analysis', value: 'data-analysis' },
  { label: 'Digital Marketing', value: 'd-marketing' },
  { label: 'Environmental Consulting', value: 'e-consulting' },
  { label: 'Finance', value: 'finance' },
  { label: 'Financial Services', value: 'financial-services' },
  { label: 'Financial Technology', value: 'f-technology' },
  { label: 'Healthtech Consulting', value: 'h-consulting' },
  { label: 'Healthcare Management', value: 'h-management' },
  { label: 'Human Resources Consulting', value: 'hr-consulting' },
  { label: 'Investment Banking', value: 'i-banking' },
  { label: 'Law', value: 'law' },
  { label: 'Management Consulting', value: 'm-consulting' },
  { label: 'Marketing', value: 'marketing' },
  { label: 'Product Design', value: 'product-design' },
  { label: 'Product Management', value: 'product-management' },
  { label: 'Project Management', value: 'project-management' },
  { label: 'Public Relations', value: 'public-relations' },
  { label: 'Social Impact Consulting', value: 'sm-consulting' },
  { label: 'Software Development', value: 'software-development' },
  { label: 'Software Engineering', value: 'software-engineering' },
  { label: 'Strategy Consulting', value: 's-consulting' },
  { label: 'Tax M&A', value: 'tax-ma' },
  { label: 'Technology Consulting', value: 't-consulting' },
  { label: 'UX Design', value: 'ux-design' },
  { label: 'Wholesale Credit', value: 'wholesale-credit' }
];
