module.exports = [
  'N/A',
  'Accounting',
  'Advertising',
  'Brand Marketing',
  'Brand Strategy',
  'Business Analytics',
  'Business Development',
  'Business Operations',
  'Communications',
  'Consulting',
  'Corporate Strategy',
  'Corporate Banking',
  'Corporate Law',
  'Data Analysis',
  'Digital Marketing',
  'Entrepreneurship',
  'Environmental Consulting',
  'Finance',
  'Financial Services',
  'Financial Technology',
  'Healthtech Consulting',
  'Healthcare Management',
  'Human Resources Consulting',
  'Investment Banking',
  'Law',
  'Management Consulting',
  'Marketing',
  'Marketing Strategy',
  'Private Equity',
  'Product Design',
  'Product Management',
  'Product Marketing',
  'Project Management',
  'Public Relations',
  'Real Estate',
  'Social Impact Consulting',
  'Software Development',
  'Software Engineering',
  'Strategy & Analytics',
  'Strategy Consulting',
  'Tax M&A',
  'Technology Consulting',
  'UI/UX Design',
  'Wholesale Credit'
];
