module.exports = [
  'N/A',
  'Active',
  'Chapter Secretary',
  'Director of Alumni Relations',
  'Director of Brotherhood',
  'Director of Content Marketing',
  'Director of Digital Marketing',
  'Director of External Recruitment',
  'Director of External Relations',
  'Director of Internal Recruitment',
  'Director of Philanthropy',
  'Director of Professional Development',
  'Director of Projects',
  'Director of Scholarship',
  'Director of Technology',
  'Prospective Member Trainer',
  'President',
  'Vice President of Administration',
  'Vice President of Finance',
  'Vice President of Human Resources',
  'Vice President of Marketing',
  'Vice President of Professional Development',
  'Vice President of Public Relations'
];
