module.exports = [
  'N/A',
  'Active',
  'Chapter Secretary',
  'Director of Alumni Relations',
  'Director of Content Marketing',
  'Director of Digital Marketing',
  'Director of Media Content',
  'Director of Finance',
  'Director of External Recruitment',
  'Director of External Relations',
  'Director of Internal Recruitment',
  'Director of Operations',
  'Director of Partnerships',
  'Director of Philanthropy',
  'Director of Professional Development',
  'Director of Scholarship',
  'Director of Technology',
  'Project Manager',
  'Prospective Member Trainer',
  'President',
  'Social Director',
  'Vice President of Administration',
  'Vice President of Finance',
  'Vice President of Human Resources',
  'Vice President of Marketing',
  'Vice President of Professional Development',
  'Vice President of Public Relations'
];
