module.exports = [
  'N/A',
  'Applied Mathematics',
  'Business Administration',
  'Cognitive Science',
  'Computer Science',
  'Data Science',
  'Economics',
  'English',
  'Environmental Economics and Policy',
  'Environmental Science',
  'EECS',
  'French',
  'Media Studies',
  'Political Economy',
  'Political Science',
  'Psychology',
  'Public Health',
  'Spanish',
  'Statistics',
  'Sustainable Environmental Design'
];
