module.exports = [
  { label: 'N/A', value: '' },
  { label: 'Applied Mathematics', value: 'applied-math' },
  { label: 'Business Administration', value: 'business' },
  { label: 'Cognitive Science', value: 'cog-sci' },
  { label: 'Computer Science', value: 'comp-sci' },
  { label: 'Data Science', value: 'data-sci' },
  { label: 'Economics', value: 'econ' },
  { label: 'English', value: 'english' },
  { label: 'Environmental Economics and Policy', value: 'eep' },
  { label: 'Environmental Science', value: 'enviro-sci' },
  { label: 'EECS', value: 'eecs' },
  { label: 'French', value: 'french' },
  { label: 'Media Studies', value: 'media-studies' },
  { label: 'Political Economy', value: 'poli-econ' },
  { label: 'Political Science', value: 'poli-sci' },
  { label: 'Psychology', value: 'psych' },
  { label: 'Public Health', value: 'public-health' },
  { label: 'Spanish', value: 'spanish' },
  { label: 'Statistics', value: 'stats' },
  { label: 'Sustainable Environmental Design', value: 'sus-env-des' }
];
