module.exports = [
  'N/A',
  'Applied Mathematics',
  'Business Administration',
  'City Planning',
  'Cognitive Science',
  'Computer Science',
  'Data Science',
  'Economics',
  'English',
  'Environmental Economics and Policy',
  'Environmental Science',
  'EECS',
  'French',
  'Global Studies',
  'History',
  'Industrial Engineering & Operations Research',
  'Intended Business Administration',
  'Italian',
  'Legal Studies',
  'Linguistics',
  'Logic',
  'Media Studies',
  'Political Economy',
  'Political Science',
  'Psychology',
  'Public Health',
  'Spanish',
  'Statistics',
  'Sustainable Environmental Design'
];
